# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e091e54f710b307d2500ae0a8f94d15be3a9664a4d8c487979c1f9457c820085146c4376205d1aaa1cc743411e94b6c33360bd515b8679f28ae67029f3b1a67d

test:
  secret_key_base: b4f6d7d3b179bf54c0b9c9281b35443f0fa5094dfbb14e7b50e9774f30850bbf9ae04334223179f689fcf0b780b1fcaafa787eb2977bf85b95a1f941437135c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
